---
- name: install apache
  yum:
    name: httpd
    state: present
- name: enable cors
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: 'Header set Access-Control-Allow-Origin "*"'
    # regexp: '<Directory "/var/www/html">'
    insertafter: '<Directory "/var/www/html">'
- name: enable range requests
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: 'Header set Access-Control-Allow-Headers Range'
    insertafter: 'Header set Access-Control-Allow-Origin "*"'
- name: remove firewall
  yum:
    name: firewalld
    state: removed
- name: symlink /var/www/html/v to /vagrant/tmp
  file:
    path: /var/www/html/v
    src: /vagrant/tmp
    state: link
    force: yes
- name: restart httpd
  service: name=httpd state=restarted
- name: enable httpd
  service:
    name: httpd
    enabled: yes
