---
- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present 
  become: yes

- name: Install Linuxbrew prerequisites for Red Hat or CentOS
  yum:
    update_cache: yes
    pkg: "{{ item }}"
    state: installed
  with_items:
    - curl 
    - file 
    - git 
    - python-setuptools
  become: yes

- name: Install linuxbrew with git
  become: no
  git: 
    repo: https://github.com/Linuxbrew/brew.git 
    dest: ~/.linuxbrew
    clone: yes
    depth: 1
    accept_hostkey: yes
    update: no

- name: Load Linuxbrew automatically in ~/.bash_profile
  become: no
  lineinfile: >
    dest="~/.bash_profile"
    line="{{ item }}"
    create=yes
    state=present
  with_items:
    - PATH="$HOME/.linuxbrew/bin:$PATH"
    - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
    - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"

#     - homebrew:
##         name: ffmpeg 
#        state: present
#        install_options: with-x264, with-x265, with-fdk-aac, with-libmp3lame, with-opus, with-libogg, with-libvorbis, with-libvpx
#        update_homebrew: yes
#      environment:
#        PATH: "~/.linuxbrew/bin:{{ ansible_env.PATH }}"