---
- name: download and unzip bento4
  unarchive:
    src: http://zebulon.bok.net/Bento4/binaries/Bento4-SDK-1-5-0-613.x86_64-unknown-linux.zip
    dest: "/home/{{ansible_user}}/"
    remote_src: yes

- name: move bento4
  command: "mv /home/{{ansible_user}}/Bento4-SDK-1-5-0-613.x86_64-unknown-linux/ /usr/local/bento4/"
  args:
    creates: "/usr/local/bento4"

- name: set permissions on /usr/local/bento4/
  file:
    path: /usr/local/bento4/
    mode: "u=rwx,go=rx"
